# This is a basic workflow to help you get started with Actions

name: Java-CI

# Controls when the action will run. Triggers the workflow on push and pull request
# events, for all branches.
on:
  [ pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Here is the "build" job
  build&run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:  
      DISPLAY: ':99'
    # Steps to be executed
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
    - uses: actions/checkout@v2
      # Compile the java code, first to be ran
    - name: Compile the java code
      working-directory: ./snake/
      run: javac -d . *.java
    - name: Setup headless environment
      run: Xvfb :99 &
    - name: Run the java code
      working-directory: ./snake/
      run: java ps.SnakeApp2D &
    - name: Kill the application after 30s
      run: |
        sleep 30
        kill -9 $(pidof java ps.SnakeApp2D)
